version: '3.4'

services:
  eshopwebmvc:
    image: eshopcontregtask8.azurecr.io/eshopwebmvc
    build:
      context: .
      dockerfile: src/Web/Dockerfile
  eshoppublicapi:
    image: eshopcontregtask8.azurecr.io/eshoppublicapi
    build:
      context: .
      dockerfile: src/PublicApi/Dockerfile